export interface UploadCar{
    carName: string,
    carModel: string,
    carType: string,
    yearName: string,
    carYearMake: number,
    carTransmission: string,
    carEngineType: string,
    carNoOfGears: number,
    carHorsePower: number,
    carTorque: number,
    carKilowatts: number,
    carEngineSize: number,
    carNoOfSeats: number,
    carFuelConsuption: number,
    carFuelTankSize: number,
    carAcceleration: number,
    carPrice: number,
    carFeaturedImageUrl: string,
    urlHandle: string,
    author: string
}